### ISSUE TITLE
Mintaszövegek gyűjtése

### ISSUE THREAD

**Issue by csaladenes** [szekelydata/blog#35]

**Comment by vbibolya** [comment]
![nehezen megfejtheto kezirat](https://cloud.githubusercontent.com/assets/28129440/25612917/c0facb16-2f2c-11e7-8d11-69335044658c.jpg)
![kezirat](https://cloud.githubusercontent.com/assets/28129440/25612916/c0ee6d8a-2f2c-11e7-8fa2-af1e7c4105f8.jpg)
